
INSERT INTO film (film_id, title, description, release_year, language_id, rental_duration, rental_rate, length, replacement_cost, rating)
VALUES
(1, 'Bol', 'A female speaker, respected in her community, must confront the harsh realities of her society when her husband takes a second wife.', 2011, 1, 3, 2.99, 4.5, 'PG-13'),
(2, 'Waar', 'The efforts of the Pakistani security forces in their fight against terrorism and how the lives of security officials are affected.', 2013, 1, 2, 2.99, 4.0, 'R'),
(3, 'Dukhtar', 'A mother kidnaps her 10-year-old daughter to save her from the fate of marrying her cousin in a remote village in Pakistan.', 2014, 1, 3, 2.99, 4.0, 'PG-13'),
(4, 'Manto', 'The film is based on the life of Urdu writer Saadat Hasan Manto, who is known for his bold and daring writings.', 2015, 1, 3, 2.99, 4.0, 'R'),
(5, 'Ho Mann Jahaan', 'Three friends, who are struggling to make a name in the music industry, find love and fame in the city of Karachi.', 2015, 1, 2, 2.99, 4.0, 'PG-13'),
(6, 'Lahore Se Aagey', 'A road trip from Lahore to Karachi, filled with music, romance, and self-discovery.', 2016, 1, 2, 2.99, 3.5, 'PG-13'),
(7, 'Actor in Law', 'A young actor, who is struggling to make a name in the film industry, finds himself in a series of comedic misadventures.', 2016, 1, 2, 2.99, 3.5, 'PG-13'),
(8, 'Verna', 'A young woman, who is a rape victim, seeks revenge against her perpetrators.', 2017, 1, 3, 2.99, 4.0, 'R'),
(9, 'Punjab Nahi Jaungi', 'A romantic comedy about a young man, who is struggling to find love, and his adventures in Lahore and London.', 2017, 1, 2, 2.99, 3.5, 'PG-13'),
(10, 'Cake', 'A family drama about a young woman, who returns to her hometown in Karachi, and her struggles to reconnect with her family.', 2018, 1, 3, 2.99, 4.0, 'PG-13'),
(11, 'Lagaan', 'The people of a small village in Victorian India stake their future on a cricket match to raise money to pay off their taxes.', 2001, 3, 3, 2.99, 4.5, 'PG'),
(12, 'Swades', 'A successful Indian scientist returns to an Indian village to take his nanny to America with him and in the process rediscovers his roots.', 2004, 3, 3, 2.99, 4.5, 'PG'),
(13, 'Rang De Basanti', 'The story of six young Indians who rebel against the system after the death of a friend.', 2006, 3, 3, 2.99, 4.5, 'PG-13'),
(14, 'Taare Zameen Par', 'An eight-year-old boy is thought to be lazy and a trouble-maker, until a new art teacher has the patience and compassion to discover the real problem behind his struggles in school.', 2007, 3, 3, 2.99, 4.5, 'PG'),
(15, 'Chak De! India', 'The former captain of the Indian women hockey team returns to coach a team that includes the daughter of his former lover.', 2007, 3, 3, 2.99, 4.5, 'PG'),
(16, 'Ghajini', 'A short-term memory loss patient sets out to avenge the death of his beloved.', 2008, 3, 3, 2.99, 4.5, 'R'),
(17, '3 Idiots', 'Two friends embark on a quest for a lost buddy. On this journey, they encounter a long forgotten bet, a wedding they must crash, and a funeral that goes impossibly out of control.', 2009, 3, 3, 2.99, 4.5, 'PG-13'),
(18, 'My Name Is Khan', 'An Indian Muslim man with Aspergers syndrome takes a challenge to speak to the President seriously, and embarks on a cross-country journey.', 2010, 3, 3, 2.99, 4.5, 'PG-13'),
(19, 'Peepli Live', 'A satirical look at Indias electoral politics, the media, and the apathy of the masses.', 2010, 3, 3, 2.99, 4.5, 'PG-13'),
(20, 'Udaan', 'After being abandoned for eight straight years in boarding school, a 17-year-old prodigal son returns to his dysfunctional family and tries to reconcile.', 2010, 3, 3, 2.99, 4.5, 'PG-13'),
(21, 'PK', 'An alien who comes to Earth on a research mission becomes stranded and must find a way to communicate with humans.', 2014, 3, 3, 2.99, 4.5, 'PG-13'),
(22, 'The Lunchbox', 'A mistaken delivery in Mumbais famously efficient lunchbox delivery system connects an unlikely old man to a young housewife.', 2013, 3, 3, 2.99, 4.5, 'PG'),
(23, 'Pulp Fiction', 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 1994, 5, 3, 3.99, 4.5, 'R'),
(24, 'The Dark Knight', 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, the caped crusader must come to terms with one of the greatest psychological tests of his ability to fight injustice.', 2008, 5, 3, 3.99, 5.0, 'PG-13'),
(25, 'Schindlers List', 'In German-occupied Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazi Germans.', 1993, 5, 7, 2.99, 5.0, 'R'),
(26, 'Casablanca', 'Set in unoccupied Africa during the early days of World War II: An American expatriate meets a former lover, with unforeseen complications.', 1942, 5, 3, 3.99, 4.5, 'PG'),
(27, 'Star Wars: Episode V - The Empire Strikes Back', 'After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued across the galaxy by the evil Darth Vader.', 1980, 5, 3, 3.99, 5.0, 'PG'),
(28, 'The Lord of the Rings: The Return of the King', 'Gandalf and Aragorn lead the World of Men against Sauron\s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.', 2003, 5, 7, 2.99, 5.0, 'PG-13'),
(29, 'The Matrix', 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.', 1999, 5, 2, 2.99, 4.5, 'R'),
(30, 'The Shawshank Redemption', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 1994, 5, 7, 2.99, 4.5, 'R'),
(31, 'The Godfather', 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', 1972, 5, 5, 4.99, 5.0, 'R'),
(32, 'Carry On Jatta', 'A comedy film about a man who pretends to be in love with a woman to please his family, but things get complicated when he actually falls in love with her cousin.', 2012, 2, 7, 3.99, 145, 12.99, 'PG-13'),
(33, 'Sardaar Ji', 'A supernatural comedy film about a man who falls in love with a ghost and must find a way to bring her back to life.', 2015, 2, 5, 2.99, 135, 9.99, 'PG-13',),
(34, 'Bambukat', 'A period drama film about a man who falls in love with a woman from a higher social class and must navigate the challenges of their different backgrounds.', 2016, 2, 5, 2.99, 155, 9.99, 'PG-13'),
(35, 'Manje Bistre', 'A comedy film about a man who falls in love with a woman at a traditional Punjabi wedding and must win her familys approval.', 2017, 2, 5, 2.99, 150, 9.99, 'PG-13'),
(36, 'Jatt & Juliet', 'A romantic comedy film about a Sikh man and a white woman who fall in love despite their cultural differences.', 2012, 2, 5, 2.99, 118, 9.99, 'PG-13')
(37, 'Barakah Meets Barakah', 'A romantic comedy film about a man who falls in love with a woman from a higher social class and must navigate the challenges of their different backgrounds.', 2016, 4, 5, 2.99, 88, 9.99, 'PG-13'),
(38, 'Theeb', 'A drama film about a young boy who accompanies a British officer on a perilous journey across the desert.', 2014, 4, 5, 2.99, 100, 9.99, 'PG-13'),
(39, 'Omar', 'A drama film about a young man who is accused of murder and must navigate the complexities of the Palestinian justice system.', 2013, 4, 5, 2.99, 96, 9.99, 'PG-13'),
(40, 'The Idol', 'A biographical drama film about a young man who becomes a famous singer in Palestine.', 2015, 4, 5, 2.99, 100, 9.99, 'PG'),
(41, 'Wadjda', 'A drama film about a young girl who dreams of buying a bicycle and competing in a Koran recitation competition.', 2012, 4, 5, 2.99, 98, 9.99, 'PG');
